{
 "title": "Air Quality",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Indoor Air Quality Index (0-99)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "IAQ",
     "measurement": "mqtt_consumer",
     "query": "SELECT \"IAQ\" FROM \"mqtt_consumer\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "IAQ" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "IAQ",
     "measurement": "mqtt_consumer",
     "query": "SELECT \"IAQ\" FROM \"mqtt_consumer\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "IAQ" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "IAQ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "IAQ",
     "measurement": "mqtt_consumer",
     "query": "SELECT \"IAQ\" FROM \"mqtt_consumer\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "IAQ" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  { "title": "CO2", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "co2",
     "measurement": "mqtt_consumer",
     "query": "SELECT \"co2\" FROM \"mqtt_consumer\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "co2" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 3, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "co2",
     "measurement": "mqtt_consumer",
     "query": "SELECT \"co2\" FROM \"mqtt_consumer\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "co2" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "CO2",
   "type": "graph",
   "gridPos": { "h": 6, "w": 17, "x": 7, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "co2",
     "measurement": "mqtt_consumer",
     "select": [
      [
       { "params": [ "co2" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  { "title": "PM25 (fine particles)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "pm25 standard",
     "measurement": "mqtt_consumer",
     "select": [
      [
       { "params": [ "pm25 standard" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 3, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "pm25 standard",
     "measurement": "mqtt_consumer",
     "select": [
      [
       { "params": [ "pm25 standard" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "PM25",
   "type": "graph",
   "gridPos": { "h": 6, "w": 17, "x": 7, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "pm25 standard",
     "measurement": "mqtt_consumer",
     "select": [
      [
       { "params": [ "pm25 standard" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  { "title": "PM10 (particulates)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "pm10 standard",
     "measurement": "mqtt_consumer",
     "select": [
      [
       { "params": [ "pm10 standard" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 3, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "pm10 standard",
     "measurement": "mqtt_consumer",
     "select": [
      [
       { "params": [ "pm10 standard" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "PM10",
   "type": "graph",
   "gridPos": { "h": 6, "w": 17, "x": 7, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "pm10 standard",
     "measurement": "mqtt_consumer",
     "select": [
      [
       { "params": [ "pm10 standard" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  { "title": "Environmental", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Humidity",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "humidity",
     "measurement": "mqtt_consumer",
     "select": [
      [
       { "params": [ "humidity" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 2, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "temperature",
     "measurement": "mqtt_consumer",
     "query": "SELECT ((\"temperature\" * 1.8) + 32) FROM \"mqtt_consumer\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 4, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "temperature",
     "measurement": "mqtt_consumer",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "temperature",
     "measurement": "mqtt_consumer",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  { "title": "Particles", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Particles 03um",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "particles 03um",
     "measurement": "mqtt_consumer",
     "select": [
      [
       { "params": [ "particles 03um" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Particles 05um",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "particles 05um",
     "measurement": "mqtt_consumer",
     "select": [
      [
       { "params": [ "particles 05um" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Particles 10um",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "particles 10um",
     "measurement": "mqtt_consumer",
     "select": [
      [
       { "params": [ "particles 10um" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Particles 25um",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "particles 25um",
     "measurement": "mqtt_consumer",
     "select": [
      [
       { "params": [ "particles 25um" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Particles 50um",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "particles 50um",
     "measurement": "mqtt_consumer",
     "select": [
      [
       { "params": [ "particles 50um" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Particles 100um",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "particles 100um",
     "measurement": "mqtt_consumer",
     "select": [
      [
       { "params": [ "particles 100um" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}